CREATE TABLE IF NOT EXISTS button_clicks (
  id SERIAL PRIMARY KEY,
  user_fid INTEGER NOT NULL,
  button_value VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
